# Define configuration variables here
GAME_VERSION = '0.1a'

RESOURCES_DIR = 'data'

DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
DISPLAY_NAME = 'Robie the Robot'
DISPLAY_FBDEV = '/dev/fb0'

TARGET_FPS = 120

START_MENU_IMAGE = 'start-screen.png'
START_MENU_RECT = (0.375, 0.625, 0.25, 0.25)
START_MENU_MUSIC = 'Sonic_CD_The_Jazzy_Cosmos_OC_ReMix'

PAUSE_MENU_IMAGE = 'pause-screen.png'
PAUSE_MENU_RECT = (0.25, 0.4, 0.5, 0.2)

CREDITS_FILE = 'credits.txt'

TEXT_COLOUR = (255, 255, 255)
TEXT_COLOUR_INACTIVE = (128, 128, 128)
TEXT_BACKGROUND = None
TEXT_SIZE = 20
DIALOG_BORDER = (255, 255, 255)  # White
DIALOG_BORDER_THICKNESS = 5
DIALOG_BACKGROUND = (0, 0, 128)  # Blue
DIALOG_HEIGHT = 0.4  # Fraction of the screen

DEFAULT_MAP = 'grasslands'
MAP_ENTRANCE = 'player_start'

HERO_NAME = 'robie'

BASE_MOVE_SPEED = 200  # Pixels per second
BASE_ANIMATION_SPEED = 0.2  # Seconds per frame

DEFAULT_SPRITE_WIDTH = 32
DEFAULT_SPRITE_HEIGHT = 32
ALPHA_COLOUR = (0, 255, 0)

KNOCKBACK_TIME = 0.25
INVULNERABILITY_TIME = 1.0

WEAPON_SPEED_MIN = 1
WEAPON_SPEED_MAX = 10
WEAPON_SPEED_SLOWEST = 1.0  # Seconds
WEAPON_SPEED_FASTEST = 0.1  # Seconds

FADE_TIME = 1.0  # Seconds
FADE_COLOUR = (0, 0, 0)  # Black
