# Define configuration variables here
GAME_VERSION = '0.1a'

RESOURCES_DIR = 'data'

DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
DISPLAY_NAME = 'Robie the Robot'
DISPLAY_FBDEV = '/dev/fb0'

HERO_SPRITESHEET = 'robie-spritesheet.png'
HERO_MOVE_SPEED = 200  # pixels per second
HERO_ANIMATION_SPEED = 20 # ticks per frame
SPRITE_WIDTH = 32
SPRITE_HEIGHT = 32
ALPHA_COLOUR = (0, 255, 0)

DEFAULT_MAP = 'grasslands'

TEXT_COLOUR = (255, 255, 255)
TEXT_BACKGROUND = None
TEXT_SIZE = 20
DIALOG_BORDER = (255, 255, 255)
DIALOG_BORDER_THICKNESS = 5
DIALOG_BACKGROUND = (0, 0, 128)
DIALOG_HEIGHT = 0.4 # Fraction of the screen
